## Perform vectorized implementation of simple matrix operation like finding the transpose of a matrix, adding, subtracting or multiplying two matrices.

In [1]:
import numpy as np

In [2]:
A = np.array(
    [[1, 6, 4],
     [2, 1, -4]])
B = np.array(
    [[1, 2, 3],
     [5, 7, -2]])
C = np.array(
    [[2, 4],
     [1, 7],
     [2, 1]])

In [3]:
print(A.T)

[[ 1  2]
 [ 6  1]
 [ 4 -4]]


In [4]:
print(B.T)

[[ 1  5]
 [ 2  7]
 [ 3 -2]]


In [5]:
print(C.T)

[[2 1 2]
 [4 7 1]]


In [6]:
print(A + B)

[[ 2  8  7]
 [ 7  8 -6]]


In [7]:
print(A - B)

[[ 0  4  1]
 [-3 -6 -2]]


In [8]:
print(B - A)

[[ 0 -4 -1]
 [ 3  6  2]]


In [9]:
print(np.dot(A, C))

[[16 50]
 [-3 11]]
