#### Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix.

In [1]:
import math
import numpy as np

In [2]:
A = np.array(
    [[ 1, 4, -6, 7],
     [-2, -1, 3, 2],
     [-1, 4, 3, 7]])

In [3]:
B = np.absolute(A)
print(B)

[[1 4 6 7]
 [2 1 3 2]
 [1 4 3 7]]


In [4]:
C = -A
print(C)

[[-1 -4  6 -7]
 [ 2  1 -3 -2]
 [ 1 -4 -3 -7]]


In [5]:
# adding a row
D = np.insert(A, 1, [1, 4, 4, 2], axis = 0)
print(D)

[[ 1  4 -6  7]
 [ 1  4  4  2]
 [-2 -1  3  2]
 [-1  4  3  7]]


In [6]:
# inserting a column
D = np.insert(D, 3, [1, 2, 3, 8], axis = 1)
print(D)

[[ 1  4 -6  1  7]
 [ 1  4  4  2  2]
 [-2 -1  3  3  2]
 [-1  4  3  8  7]]


In [7]:
# deleting a row
D = np.delete(D, 0, axis = 0)
print(D)

[[ 1  4  4  2  2]
 [-2 -1  3  3  2]
 [-1  4  3  8  7]]


In [8]:
# deleting columns 1, 2 and 3
D = np.delete(D, range(1, 4), axis = 1)
print(D)

[[ 1  2]
 [-2  2]
 [-1  7]]
