## Create/Define single dimension/multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

### Zeros

In [1]:
import numpy as np

In [2]:
print(np.zeros(3))

[0. 0. 0.]


In [3]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones

In [4]:
print(np.ones(3))

[1. 1. 1.]


In [5]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4x5 Matrix of random numbers between 50 and 100

In [6]:
np.random.rand(20).reshape(4, 5) * 50 // 1 + 49

array([[68., 52., 82., 68., 78.],
       [88., 51., 52., 50., 59.],
       [68., 86., 78., 68., 94.],
       [65., 60., 75., 71., 89.]])

### 4x4 random diagonal matrix

In [7]:
n = 4
vec = np.random.choice(range(50), n)
mat = np.diag(vec)
print(mat)

[[40  0  0  0]
 [ 0  8  0  0]
 [ 0  0 31  0]
 [ 0  0  0 38]]
