## Use some function for neural networks, like Stochastic Gradient Descent or backpropagation algorithm to predict the value of a variable based on the dataset of problem 14.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 666us/step - loss: 0.6332 - accuracy: 0.6746
Epoch 2/100
250/250 [==============================] - 0s 678us/step - loss: 0.4752 - accuracy: 0.8020
Epoch 3/100
250/250 [==============================] - 0s 674us/step - loss: 0.4391 - accuracy: 0.8112
Epoch 4/100
250/250 [==============================] - 0s 714us/step - loss: 0.4227 - accuracy: 0.8158
Epoch 5/100
250/250 [==============================] - 0s 671us/step - loss: 0.4087 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 0s 670us/step - loss: 0.3946 - accuracy: 0.8269
Epoch 7/100
250/250 [==============================] - 0s 679us/step - loss: 0.3822 - accuracy: 0.8366
Epoch 8/100
250/250 [==============================] - 0s 714us/step - loss: 0.3726 - accuracy: 0.8429
Epoch 9/100
250/250 [==============================] - 0s 666us/step - loss: 0.3663 - accuracy: 0.8447
Epoch 10/100
250/250 [==============================] - 0s 650us/step - l

250/250 [==============================] - 0s 842us/step - loss: 0.3334 - accuracy: 0.8616
Epoch 78/100
250/250 [==============================] - 0s 802us/step - loss: 0.3335 - accuracy: 0.8624
Epoch 79/100
250/250 [==============================] - 0s 794us/step - loss: 0.3333 - accuracy: 0.8606
Epoch 80/100
250/250 [==============================] - 0s 886us/step - loss: 0.3331 - accuracy: 0.8625
Epoch 81/100
250/250 [==============================] - 0s 762us/step - loss: 0.3332 - accuracy: 0.8634
Epoch 82/100
250/250 [==============================] - 0s 634us/step - loss: 0.3335 - accuracy: 0.8624
Epoch 83/100
250/250 [==============================] - 0s 634us/step - loss: 0.3334 - accuracy: 0.8615
Epoch 84/100
250/250 [==============================] - 0s 626us/step - loss: 0.3330 - accuracy: 0.8618
Epoch 85/100
250/250 [==============================] - 0s 651us/step - loss: 0.3331 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 0s 758us/step - loss:

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [16]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1513   82]
 [ 198  207]]


In [18]:
acc = (cm[0][0] + cm[1][1]) / 2000

In [19]:
acc

0.86

In [20]:
print(round(acc * 100, 2))

86.0


In [21]:
sgd = SGDClassifier()
sgd.fit(X_train, y_train.ravel())
y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_train, y_train) * 100, 2)
acc_sgd

80.95

In [22]:
round(sgd.score(X_test, y_test) * 100, 2)

81.0