## Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix.

In [1]:
import numpy as np

In [2]:
A = np.array(
    [[1, 2, 4, 4],
     [4, 7, 5, 1],
     [2, 6, 8, 5]])

In [3]:
B = np.array(
    [[8, 9, 0, 6],
     [2, 1, 4, 4],
     [2, 4, 6, 8]])

### Matrix addition

In [4]:
print("A + B =\n", (A + B))

A + B =
 [[ 9 11  4 10]
 [ 6  8  9  5]
 [ 4 10 14 13]]


### Matrix subtraction

In [5]:
print("A - B =\n", (A - B))

A - B =
 [[-7 -7  4 -2]
 [ 2  6  1 -3]
 [ 0  2  2 -3]]


In [6]:
C = np.array(
    [[1, 9, 7],
     [2, 4, 4],
     [2, 6, 8]])

In [7]:
D = np.array(
    [[8, 9, 0],
     [2, 1, 4],
     [2, 4, 6]])

### Matrix multiplication

In [8]:
print("C * D =")
print(np.dot(C, D))

C * D =
[[40 46 78]
 [32 38 40]
 [44 56 72]]


### Elements of column 1 (indexing starts from 0)

In [9]:
print(A[:, 1].reshape(3, 1))

[[2]
 [7]
 [6]]


### Elements of column 0 and 3 (indexing starts from 0)

In [10]:
print(A[:, [0, 3]])

[[1 4]
 [4 1]
 [2 5]]


### Elements of all columns except the last column (indexing starts from 0)

In [11]:
print(A[:, 0:-1])

[[1 2 4]
 [4 7 5]
 [2 6 8]]
