### 1. Perform elementary mathematical operations in Octave/MATLAB like addition,multiplication, division and exponentiation.

In [1]:
num1 = 6
num2 = 2

print(f"Addition: {num1 + num2}")
print(f"Subtraction: {num1 - num2}")
print(f"Multiplication: {num1 * num2}")
print(f"Division: {num1 / num2}")
print(f"Exponentiation: {num1 ** num2}")

Addition: 8
Subtraction: 4
Multiplication: 12
Division: 3.0
Exponentiation: 36


### 2. Perform elementary logical operations in Octave/MATLAB (like OR, AND, Checking forEquality, NOT, XOR).

In [2]:
num1 = 1
num2 = 0
and_result = num1 & num2
print(f"AND Operation: {and_result}")
or_result = num1 | num2
print(f"OR Operation: {or_result}")
equality_result = num1 == num2
print(f"Equality: {equality_result}")
not_result =  not num2
print(f"NOT Operation: {not_result}")
xor_result = num1 ^ num2
print(f"XOR Operation: {xor_result}")

AND Operation: 0
OR Operation: 1
Equality: False
NOT Operation: True
XOR Operation: 1


### 3. Create, initialize and display simple variables and simple strings and use simple formatting for variable.

In [3]:
num1 = 3
num2 = 4
boolean = False

print(num1)
print(num2)
print(boolean)

name = "Python"
print(name)

print(name.lower())
print(name.upper())
print(name.capitalize())
print(name.isalnum())
print(name.replace("B", "b"))

3
4
False
Python
python
PYTHON
Python
True
Python


###  4. Create/Define single dimension / multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

In [4]:
import numpy as np

In [5]:
mat_sin = np.array([1,2,4])
mat_sin

array([1, 2, 4])

In [6]:
mat_mul = np.matrix([[1,2,3], [3,4,5]])
mat_mul

matrix([[1, 2, 3],
        [3, 4, 5]])

In [7]:
np.ones(shape = (3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.zeros(shape = (4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.random.randint(low = 0,
           high = 100, 
           size = (3,5))

array([[55, 77, 17, 23, 51],
       [16, 26, 98, 11, 93],
       [21, 30, 60, 51, 14]])

In [10]:
np.diag([3,4,6])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

### 5. Use command to compute the size of a matrix, size/length of a particular row/column, load data from a text file, store matrix data to a text file, finding out variables and their features in the current scope

In [11]:
mat = np.random.randint(low = 0,
                        high = 100, 
                        size = (3,5))
mat.shape, mat.shape[0], mat.shape[1]

((3, 5), 3, 5)

In [12]:
with open("output.txt", "w") as file:
    np.savetxt(file, tuple(mat))

In [13]:
with open("output.txt", "r") as file:
     lines = np.loadtxt(file)
lines

array([[98., 57., 71., 97.,  2.],
       [78., 34.,  8., 68., 59.],
       [ 8., 19., 10., 84., 35.]])