In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
mat1 = np.random.randn(5,6)
mat1

array([[ 0.56461613,  1.6876502 , -1.66521647, -1.4738274 ,  0.46500777,
        -0.86085178],
       [-0.16300344, -0.03031835,  0.16698367, -1.31662031, -0.10367424,
        -0.51047334],
       [-0.45200118, -0.72235022,  0.51692959,  0.20071581,  0.52461477,
        -0.7056483 ],
       [ 0.27684797,  1.16874322,  0.60192473,  0.75204975, -1.37480848,
        -0.96074045],
       [ 0.6575736 , -0.24834669, -0.11767544,  0.00998743, -0.64246567,
        -0.80071226]])

In [3]:
mat2 = np.random.randn(5,6)
mat2

array([[-0.00281949,  1.31859009, -0.62259313,  0.5209915 ,  0.30181786,
        -1.20719921],
       [-1.38614957, -2.53908207,  0.16254225,  0.0287618 ,  0.52618107,
         0.69672685],
       [-0.52165755, -0.95996516, -0.20479601,  0.41425488,  1.24158539,
        -1.18645564],
       [-1.60489574,  1.31329632,  1.02585305, -0.23917109, -0.69824727,
        -0.86440358],
       [-1.56155181, -0.01743967, -0.26935375, -1.33492102,  1.26027105,
        -1.35894301]])

#### Addition

In [4]:
row_idx = 3
col_idx = 3

In [5]:
result = mat1 + mat2
result

array([[ 0.56179665,  3.00624028, -2.28780961, -0.9528359 ,  0.76682563,
        -2.06805099],
       [-1.54915301, -2.56940042,  0.32952592, -1.28785851,  0.42250683,
         0.18625351],
       [-0.97365873, -1.68231538,  0.31213358,  0.61497069,  1.76620016,
        -1.89210394],
       [-1.32804776,  2.48203954,  1.62777777,  0.51287866, -2.07305575,
        -1.82514403],
       [-0.90397821, -0.26578636, -0.38702919, -1.32493359,  0.61780538,
        -2.15965527]])

In [6]:
result[row_idx], result[col_idx]

(array([-1.32804776,  2.48203954,  1.62777777,  0.51287866, -2.07305575,
        -1.82514403]),
 array([-1.32804776,  2.48203954,  1.62777777,  0.51287866, -2.07305575,
        -1.82514403]))

#### Subtraction

In [7]:
row_idx = 3
col_idx = 3

In [8]:
result = mat1 - mat2
result

array([[ 0.56743562,  0.36906011, -1.04262334, -1.9948189 ,  0.16318991,
         0.34634743],
       [ 1.22314613,  2.50876371,  0.00444141, -1.3453821 , -0.62985531,
        -1.20720019],
       [ 0.06965637,  0.23761494,  0.72172559, -0.21353906, -0.71697063,
         0.48080734],
       [ 1.88174371, -0.14455309, -0.42392832,  0.99122083, -0.67656121,
        -0.09633687],
       [ 2.21912541, -0.23090701,  0.15167831,  1.34490845, -1.90273672,
         0.55823075]])

In [9]:
result[row_idx], result[col_idx]

(array([ 1.88174371, -0.14455309, -0.42392832,  0.99122083, -0.67656121,
        -0.09633687]),
 array([ 1.88174371, -0.14455309, -0.42392832,  0.99122083, -0.67656121,
        -0.09633687]))

#### Element-Wise Multiplcation

In [10]:
row_idx = 3
col_idx = 3

In [11]:
result = mat1 * mat2
result

array([[-1.59192724e-03,  2.22531882e+00,  1.03675234e+00,
        -7.67851550e-01,  1.40347652e-01,  1.03921959e+00],
       [ 2.25947147e-01,  7.69807874e-02,  2.71419010e-02,
        -3.78683681e-02, -5.45514227e-02, -3.55660481e-01],
       [ 2.35789827e-01,  6.93431041e-01, -1.05865115e-01,
         8.31475036e-02,  6.51354030e-01,  8.37220401e-01],
       [-4.44312133e-01,  1.53490617e+00,  6.17486312e-01,
        -1.79868556e-01,  9.59956266e-01,  8.30467486e-01],
       [-1.02683525e+00,  4.33108483e-03,  3.16963212e-02,
        -1.33324282e-02, -8.09680884e-01,  1.08812233e+00]])

In [12]:
result[row_idx], result[col_idx]

(array([-0.44431213,  1.53490617,  0.61748631, -0.17986856,  0.95995627,
         0.83046749]),
 array([-0.44431213,  1.53490617,  0.61748631, -0.17986856,  0.95995627,
         0.83046749]))

#### Dot Product

In [13]:
mat1 = np.random.randn(5,6)
mat2 = np.random.randn(6,3)

In [14]:
row_idx = 3
col_idx = 3

In [15]:
result = np.dot(mat1, mat2)
result

array([[ 3.90047651,  1.21796643, -0.93203899],
       [ 0.95973788,  1.77837808,  0.02557867],
       [ 1.87571065,  1.63684185, -0.3644348 ],
       [-4.54794355,  0.79807696,  3.08300501],
       [-2.95957597, -1.60147712,  1.59628807]])

In [16]:
result[row_idx], result[col_idx]

(array([-4.54794355,  0.79807696,  3.08300501]),
 array([-4.54794355,  0.79807696,  3.08300501]))

#### Transpose

In [17]:
mat1 = np.random.randn(5,6)
result = mat1.T
result

array([[ 0.60530693,  1.55407645, -0.19206076,  0.64459734, -0.86061383],
       [-2.9257535 , -0.37098433,  2.25183116,  0.4589894 ,  0.26549579],
       [-2.08842523, -0.34636098, -0.72278006, -0.13820976,  1.47985196],
       [-0.29240015, -0.29667452,  0.90267481, -0.5786054 , -0.52780917],
       [-0.54880576,  0.74819457,  0.10270093,  1.95518212, -0.94046091],
       [ 1.75803602,  0.84729635, -0.28716993, -0.09109674, -0.86889755]])